[project]
name = "django-react"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "luisOrtga", email = "ortegaluiskb@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "coreapi>=2.3.3",
    "django>=6.1.1",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.18.0",
    "drf-spectacular>=0.30.0",
]

[project.scripts]
django-react = "django_react:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
select = ["E", "F", "I"]

[tool.ruff.format]
quote-style = "single"
